<a href="https://colab.research.google.com/github/NFULL07/2025Cheonan_SmartCity_Contest/blob/main/%EC%84%A0%ED%98%95%EB%8C%80%EC%88%98%EC%8B%A4%EC%8A%B5zero.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello world!")

Hello world!


1. 파이썬 기초(Optional)

In [ ]:
# integer
x = 3
print("정수: %01d, %02d, %03d, %04d, %05d" % (x,x,x,x,x))

# float
x = 256.123
print ("실수: %.0f, %.1f, %.2f" % (x,x,x))

# string
x = "Hello, world"
print ("문자열: [%s]" % (x))

정수: 3, 03, 003, 0003, 00003
실수: 256, 256.1, 256.12
문자열: [Hello, world]


In [ ]:
contents = ["Regression", "Classifcation", "SVM", "Clustering", "Dimension reduction",
            "NN", "CNN", "AE", "GAN", "RNN"]
for con in contents:
  if con in ["Regression", "Classifcation", "SVM", "Clustering", "Dimension reduction"]:
    print ("%s은(는) 기계학습 내용입니다." %con)
  elif con in ["NN", "CNN", "AE", "GAN", "RNN"]:
    print ("%s은(는) convolutional neural network입니다." %con)
  else:
    print ("%s은(는) 심층학습 내용입니다." %con)

Regression은(는) 기계학습 내용입니다.
Classifcation은(는) 기계학습 내용입니다.
SVM은(는) 기계학습 내용입니다.
Clustering은(는) 기계학습 내용입니다.
Dimension reduction은(는) 기계학습 내용입니다.
NN은(는) convolutional neural network입니다.
CNN은(는) convolutional neural network입니다.
AE은(는) convolutional neural network입니다.
GAN은(는) convolutional neural network입니다.
RNN은(는) convolutional neural network입니다.


In [ ]:
for (i,con) in enumerate(contents):
  print ("contents[%d]: %s" %(i,con))

contents[0]: Regression
contents[1]: Classifcation
contents[2]: SVM
contents[3]: Clustering
contents[4]: Dimension reduction
contents[5]: NN
contents[6]: CNN
contents[7]: AE
contents[8]: GAN
contents[9]: RNN


In [ ]:
def sum(a,b):
  return a+b

x = 10.0
y = 20.0
print ("%.1f + %.1f = %.1f" %(x,y,sum(x,y)))

10.0 + 20.0 = 30.0


In [ ]:
a = []
b = [1,2,3]
c = ["Hello", ",", "world"]
d = [1,2,3,"x","y","z"]
x = []
print (x)

x.append('a')
print (x)

x.append(123)
print (x)

x.append(["a", "b"])
print(x)

[]
['a']
['a', 123]
['a', 123, ['a', 'b']]


In [ ]:
dic = dict()
dic["name"]="Heekyung"
dic["town"]="Goyang city"
dic["job"]="Assistant professor"
print (dic)

{'name': 'Heekyung', 'town': 'Goyang city', 'job': 'Assistant professor'}


In [ ]:
class Student:
  # 생성자
  def __init__(self, name):
    self.name = name
  # 메써드
  def study(self, hard=False):
    if hard:
      print ("%s 학생은 열심히 공부합니다." %self.name)
    else:
      print ("%s 학생은 공부합니다." %self.name)

s = Student('Heekyung')
s.study()
s.study(hard=True)

Heekyung 학생은 공부합니다.
Heekyung 학생은 열심히 공부합니다.


In [ ]:
import numpy as np

def print_val(x):
  print("Type:", type(x))
  print("Shape:", x.shape)
  print("값:\n", x)
  print(" ")

x = np.array([1, 2, 3])
print_val(x)

x[0] = 5
print_val(x)

y = np.array([[1,2,3], [4,5,6]])
print_val(y)

a = np.ones((3,2))
print_val(a)

a = np.zeros((2,2))
print_val(a)

a = np.eye(3,3)
print_val(a)

a = np.random.random((4,4))
print_val(a)

a = np.random.randn(4,4)
print_val(a)

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print_val(a)

b = a[:2, 1:3] # 행 0~1, 열 1~2
print_val(b)

row1 = a[1, :] # 1번째 행
print_val(row1)

m1 = np.array([[1,2], [3,4]])
m2 = np.array([[5,6], [7,8]])

#elementwise sum
print_val(m1+m2)
print_val(np.add(m1, m2))

# elementwise difference
print_val(m1-m2)
print_val(np.subtract(m1, m2))

# elementwise product
print_val(m1 * m2)
print_val(np.multiply(m1, m2))

# elementwise division
print_val(m1 / m2)
print_val(np.divide(m1, m2))

# elementwise square root
print_val(np.sqrt(m1))

m1 = np.array([[1,2],[3,4]]) # (2,2)
m2 = np.array([[5,6], [7,8]]) # (2,2)
v1 = np.array([9,10]) # (2,1) # [[9,10]] (1,2)
v2 = np.array([11,12]) # (2,1)

print_val(m1)
print_val(m2)
print_val(v1)
print_val(v2)

print_val(v1.dot(v2))
print_val(np.dot(v1,v2))

print_val(m1.dot(v1)) # (2,2) x (2,1) -> (2,1)
print_val(np.dot(m1, v1))

print_val(m1.dot(m2))
print_val(np.dot(m1, m2))

print_val(m1)
print_val(m1.T)

print_val(np.sum(m1)) # 행렬의 모든 원소의 합
print_val(np.sum(m1, axis=0)) # shape[0](행)을 압축시키자 (2,2) -> (2,)
print_val(np.sum(m1, axis=1)) # shape[1](열)을 압축시키자 (2,2) -> (2,)

m1 = np.array([[1,2,3], [4,5,6]])
print(m1)
print(m1.shape) # (2,3)

print(np.sum(m1))
print(np.sum(m1, axis=0)) # shape[0](행)을 압축시키자 (2,3) -> (3,)
print(np.sum(m1, axis=1)) # shape[1](열)을 압축시키자 (2,3) -> (2,)

m1 = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
              [10,11,12]])
m2 = np.zeros_like(m1) # m1과 같은 형태의 0으로 이루어진 np array
print_val(m1)
print_val(m2)

import matplotlib.pyplot as plt
%matplotlib inline

x = np.arange(0, 10, 0.1) # 0~10 까지 0.1 간격의 숫자 배열
y = np.sin(x)

plt.plot(x,y)

y_sin - np.sin(x)
y_cos = np.cos(x)

plt.plot(x,y_sin)
plt.plot(x,y_cos)
plt.xlabel('x axis label')
plt.ylabel('y axis label')
plt.title(['sin' & 'cos'])
plt.legend(['sin', 'cos'])

plt.show()

plt.subplot(2,1,1) # (2,1) 형태 플랏의 첫 번째 자리에 그리겠다
plt.plot(x,y_sin)
plt.title('sin')

plt.subplot(2,1,2)
plt.plot(x,y_cos)
plt.title('cos')

plt.show()

Type: <class 'numpy.ndarray'>
Shape: (3,)
값:
 [1 2 3]
 
Type: <class 'numpy.ndarray'>
Shape: (3,)
값:
 [5 2 3]
 
Type: <class 'numpy.ndarray'>
Shape: (2, 3)
값:
 [[1 2 3]
 [4 5 6]]
 
Type: <class 'numpy.ndarray'>
Shape: (3, 2)
값:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
 
Type: <class 'numpy.ndarray'>
Shape: (2, 2)
값:
 [[0. 0.]
 [0. 0.]]
 
Type: <class 'numpy.ndarray'>
Shape: (3, 3)
값:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 
Type: <class 'numpy.ndarray'>
Shape: (4, 4)
값:
 [[0.09926888 0.91994042 0.90286136 0.150447  ]
 [0.61501494 0.98694388 0.42097301 0.21264794]
 [0.7345606  0.26724458 0.10243539 0.99806292]
 [0.78990226 0.74850502 0.57262774 0.72044317]]
 
Type: <class 'numpy.ndarray'>
Shape: (4, 4)
값:
 [[-0.08824337 -1.00484071  0.62116703 -0.08938351]
 [-0.36296649  2.13243947 -0.03108945 -0.44291114]
 [ 0.55993801  0.76060441  1.10219237 -1.27764532]
 [ 0.17461559  1.61274175 -0.07887874 -0.43497742]]
 
Type: <class 'numpy.ndarray'>
Shape: (3, 4)
값:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12